const GRAMMAR_CARDS = [
{image:"G000.jpg",sentence:"오늘은 좀 피곤해서 집에서 쉬려고 해요.",meaning:"I’m a little tired today, so I’m planning to rest at home.",breakdown:[["오늘은","오늘 + 은","today + topic"],["좀 피곤해서","피곤하다 + -아서/어서","because I’m a little tired / so"],["집에서","집 + 에서","at home"],["쉬려고 해요","쉬다 + -려고 해요","am planning to rest"]],grammarNote:"-아서/어서 links a reason or cause to its result. -려고 해요 expresses an intention or plan."},
{image:"G001.jpg",sentence:"지금 친구를 만나러 가는데 같이 갈래요?",meaning:"I’m going to meet a friend now; do you want to come with me?",breakdown:[["지금","now","now"],["친구를 만나러 가는데","만나다 + -러 가다 + -는데","I’m going to meet a friend, and / as context"],["같이","together","together / with me"],["갈래요?","가다 + -(으)ㄹ래요?","do you want to go?"]],grammarNote:"-러 가요 expresses going somewhere in order to do something. -는데 supplies background/context. -(으)ㄹ래요? asks about willingness or preference."},
{image:"G002.jpg",sentence:"어제 산 옷이 생각보다 좀 커요.",meaning:"The clothes I bought yesterday are a little bigger than I expected.",breakdown:[["어제 산 옷이","사다 → 산 + 옷 + 이","the clothes bought yesterday + subject"],["생각보다","생각 + 보다","than expected / compared with what I thought"],["좀 커요","크다 → 커요","are a little big"]],grammarNote:"-(으)ㄴ modifies a noun with a completed/past action. 생각보다 means ‘than expected’ or ‘compared with what I thought.’"},
{image:"G003.jpg",sentence:"일이 끝나고 나서 친구랑 저녁을 먹었어요.",meaning:"After work finished, I had dinner with a friend.",breakdown:[["일이 끝나고 나서","끝나다 + -고 나서","after work finished"],["친구랑","친구 + 랑","with a friend"],["저녁을 먹었어요","먹다 → 먹었어요","ate dinner"]],grammarNote:"-고 나서 means ‘after doing’ and emphasizes that one action follows another."},
{image:"G004.jpg",sentence:"내일 비가 올 것 같아서 집에 있을 거예요.",meaning:"I think it’s going to rain tomorrow, so I’ll probably stay home.",breakdown:[["내일 비가","tomorrow + rain + subject","tomorrow, rain"],["올 것 같아서","오다 + -(으)ㄹ 것 같다 + -아서","because it looks like it will come / rain"],["집에","집 + 에","at home"],["있을 거예요","있다 + -(으)ㄹ 거예요","will / am going to stay"]],grammarNote:"-(으)ㄹ 것 같아요 expresses a prediction or impression. -(으)ㄹ 거예요 expresses a future plan or expectation."},
{image:"G005.jpg",sentence:"요즘 제가 자주 가는 가게가 있어요.",meaning:"There’s a store I’ve been going to often lately.",breakdown:[["요즘","these days","lately"],["제가 자주 가는","가다 + -는","that I often go to"],["가게가","가게 + 가","store + subject"],["있어요","있다 → 있어요","there is"]],grammarNote:"-는 modifies a noun with a present or habitual action. 이/가 있어요 expresses existence."},
{image:"G006.jpg",sentence:"시간 있을 때 보통 뭐 해요?",meaning:"What do you usually do when you have free time?",breakdown:[["시간 있을 때","있다 + -(으)ㄹ 때","when you have time"],["보통","usually","usually"],["뭐 해요?","뭐 + 하다","what do you do?"]],grammarNote:"-(으)ㄹ 때 means ‘when’ or ‘at the time when.’ This is a common conversational pattern for asking about routines."},
{image:"G007.jpg",sentence:"저는 커피보다 차를 더 자주 마셔요.",meaning:"I drink tea more often than coffee.",breakdown:[["저는","저 + 는","I + topic"],["커피보다","커피 + 보다","than coffee"],["차를","차 + 를","tea + object"],["더 자주 마셔요","더 + 자주 + 마시다","drink more often"]],grammarNote:"A보다 B를 더… compares two things: B is done or has a quality more than A."},
{image:"G008.jpg",sentence:"아직 안 먹었는데 조금 있다가 먹으려고 해요.",meaning:"I haven’t eaten yet, but I’m planning to eat in a little while.",breakdown:[["아직 안 먹었는데","안 + 먹다 + -었는데","I haven’t eaten yet, but / as background"],["조금 있다가","a little later","in a little while"],["먹으려고 해요","먹다 + -(으)려고 해요","am planning to eat"]],grammarNote:"안 negates the verb. -었는데 provides background or contrast. 조금 있다가 means ‘in a little while,’ and -(으)려고 해요 expresses intention."},
{image:"G009.jpg",sentence:"집에 가기 전에 필요한 것 좀 사야 해요.",meaning:"Before going home, I need to buy a few things I need.",breakdown:[["집에 가기 전에","가다 + -기 전에","before going home"],["필요한 것","필요하다 + -(으)ㄴ 것","things that are needed"],["좀","a few / some","softener; some"],["사야 해요","사다 + -아/어야 해요","have to / need to buy"]],grammarNote:"-기 전에 means ‘before doing.’ 것 turns a modifier into ‘thing(s).’ -아/어야 해요 expresses necessity or obligation."}
];
